/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherSalaryRouteImport } from './routes/teacher.salary'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as StudentTransactionsRouteImport } from './routes/student.transactions'
import { Route as StudentSavingsRouteImport } from './routes/student.savings'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as ParentTransactionsRouteImport } from './routes/parent.transactions'
import { Route as ParentSavingsRouteImport } from './routes/parent.savings'
import { Route as ParentInstallmentsRouteImport } from './routes/parent.installments'
import { Route as ParentFeesRouteImport } from './routes/parent.fees'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as AdminVirtualAccountsRouteImport } from './routes/admin.virtual-accounts'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSubmissionRouteImport } from './routes/admin.submission'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as AdminInstallmentsRouteImport } from './routes/admin.installments'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBillsRouteImport } from './routes/admin.bills'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherSalaryRoute = TeacherSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentTransactionsRoute = StudentTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSavingsRoute = StudentSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTransactionsRoute = ParentTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSavingsRoute = ParentSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentInstallmentsRoute = ParentInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => ParentRoute,
} as any)
const ParentFeesRoute = ParentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ParentRoute,
} as any)
const AdminVirtualAccountsRoute = AdminVirtualAccountsRouteImport.update({
  id: '/virtual-accounts',
  path: '/virtual-accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionRoute = AdminSubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstallmentsRoute = AdminInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillsRoute = AdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/bills': typeof AdminBillsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/submission': typeof AdminSubmissionRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/virtual-accounts': typeof AdminVirtualAccountsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/installments': typeof ParentInstallmentsRoute
  '/parent/savings': typeof ParentSavingsRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/savings': typeof StudentSavingsRoute
  '/student/transactions': typeof StudentTransactionsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/salary': typeof TeacherSalaryRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/bills': typeof AdminBillsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/submission': typeof AdminSubmissionRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/virtual-accounts': typeof AdminVirtualAccountsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/installments': typeof ParentInstallmentsRoute
  '/parent/savings': typeof ParentSavingsRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/savings': typeof StudentSavingsRoute
  '/student/transactions': typeof StudentTransactionsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/salary': typeof TeacherSalaryRoute
  '/admin': typeof AdminIndexRoute
  '/parent': typeof ParentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/bills': typeof AdminBillsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/submission': typeof AdminSubmissionRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/virtual-accounts': typeof AdminVirtualAccountsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/installments': typeof ParentInstallmentsRoute
  '/parent/savings': typeof ParentSavingsRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/savings': typeof StudentSavingsRoute
  '/student/transactions': typeof StudentTransactionsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/salary': typeof TeacherSalaryRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/parent'
    | '/signup'
    | '/student'
    | '/teacher'
    | '/admin/bills'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/installments'
    | '/admin/payroll'
    | '/admin/reminders'
    | '/admin/students'
    | '/admin/submission'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/virtual-accounts'
    | '/parent/dashboard'
    | '/parent/fees'
    | '/parent/installments'
    | '/parent/savings'
    | '/parent/transactions'
    | '/payment/callback'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/savings'
    | '/student/transactions'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/teacher/salary'
    | '/admin/'
    | '/parent/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/student'
    | '/admin/bills'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/installments'
    | '/admin/payroll'
    | '/admin/reminders'
    | '/admin/students'
    | '/admin/submission'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/virtual-accounts'
    | '/parent/dashboard'
    | '/parent/fees'
    | '/parent/installments'
    | '/parent/savings'
    | '/parent/transactions'
    | '/payment/callback'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/savings'
    | '/student/transactions'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/teacher/salary'
    | '/admin'
    | '/parent'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/parent'
    | '/signup'
    | '/student'
    | '/teacher'
    | '/admin/bills'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/installments'
    | '/admin/payroll'
    | '/admin/reminders'
    | '/admin/students'
    | '/admin/submission'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/virtual-accounts'
    | '/parent/dashboard'
    | '/parent/fees'
    | '/parent/installments'
    | '/parent/savings'
    | '/parent/transactions'
    | '/payment/callback'
    | '/student/dashboard'
    | '/student/fees'
    | '/student/savings'
    | '/student/transactions'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/teacher/salary'
    | '/admin/'
    | '/parent/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  PaymentCallbackRoute: typeof PaymentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/salary': {
      id: '/teacher/salary'
      path: '/salary'
      fullPath: '/teacher/salary'
      preLoaderRoute: typeof TeacherSalaryRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/transactions': {
      id: '/student/transactions'
      path: '/transactions'
      fullPath: '/student/transactions'
      preLoaderRoute: typeof StudentTransactionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/savings': {
      id: '/student/savings'
      path: '/savings'
      fullPath: '/student/savings'
      preLoaderRoute: typeof StudentSavingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/transactions': {
      id: '/parent/transactions'
      path: '/transactions'
      fullPath: '/parent/transactions'
      preLoaderRoute: typeof ParentTransactionsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/savings': {
      id: '/parent/savings'
      path: '/savings'
      fullPath: '/parent/savings'
      preLoaderRoute: typeof ParentSavingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/installments': {
      id: '/parent/installments'
      path: '/installments'
      fullPath: '/parent/installments'
      preLoaderRoute: typeof ParentInstallmentsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/fees': {
      id: '/parent/fees'
      path: '/fees'
      fullPath: '/parent/fees'
      preLoaderRoute: typeof ParentFeesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/virtual-accounts': {
      id: '/admin/virtual-accounts'
      path: '/virtual-accounts'
      fullPath: '/admin/virtual-accounts'
      preLoaderRoute: typeof AdminVirtualAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submission': {
      id: '/admin/submission'
      path: '/submission'
      fullPath: '/admin/submission'
      preLoaderRoute: typeof AdminSubmissionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/installments': {
      id: '/admin/installments'
      path: '/installments'
      fullPath: '/admin/installments'
      preLoaderRoute: typeof AdminInstallmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bills': {
      id: '/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AdminBillsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBillsRoute: typeof AdminBillsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminInstallmentsRoute: typeof AdminInstallmentsRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubmissionRoute: typeof AdminSubmissionRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminVirtualAccountsRoute: typeof AdminVirtualAccountsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillsRoute: AdminBillsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminInstallmentsRoute: AdminInstallmentsRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubmissionRoute: AdminSubmissionRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminVirtualAccountsRoute: AdminVirtualAccountsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentFeesRoute: typeof ParentFeesRoute
  ParentInstallmentsRoute: typeof ParentInstallmentsRoute
  ParentSavingsRoute: typeof ParentSavingsRoute
  ParentTransactionsRoute: typeof ParentTransactionsRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentDashboardRoute: ParentDashboardRoute,
  ParentFeesRoute: ParentFeesRoute,
  ParentInstallmentsRoute: ParentInstallmentsRoute,
  ParentSavingsRoute: ParentSavingsRoute,
  ParentTransactionsRoute: ParentTransactionsRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentSavingsRoute: typeof StudentSavingsRoute
  StudentTransactionsRoute: typeof StudentTransactionsRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentSavingsRoute: StudentSavingsRoute,
  StudentTransactionsRoute: StudentTransactionsRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherSalaryRoute: typeof TeacherSalaryRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherSalaryRoute: TeacherSalaryRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  PaymentCallbackRoute: PaymentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
