/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as ParentTransactionsRouteImport } from './routes/parent.transactions'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminInstallmentsRouteImport } from './routes/admin.installments'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTransactionsRoute = ParentTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ParentRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstallmentsRoute = AdminInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/admin': typeof AdminIndexRoute
  '/parent': typeof ParentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/installments': typeof AdminInstallmentsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/parent'
    | '/signup'
    | '/teacher'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/installments'
    | '/admin/reminders'
    | '/admin/students'
    | '/parent/dashboard'
    | '/parent/transactions'
    | '/payment/callback'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/admin/'
    | '/parent/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/installments'
    | '/admin/reminders'
    | '/admin/students'
    | '/parent/dashboard'
    | '/parent/transactions'
    | '/payment/callback'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/admin'
    | '/parent'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/parent'
    | '/signup'
    | '/teacher'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/installments'
    | '/admin/reminders'
    | '/admin/students'
    | '/parent/dashboard'
    | '/parent/transactions'
    | '/payment/callback'
    | '/teacher/dashboard'
    | '/teacher/profile'
    | '/admin/'
    | '/parent/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  SignupRoute: typeof SignupRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  PaymentCallbackRoute: typeof PaymentCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/transactions': {
      id: '/parent/transactions'
      path: '/transactions'
      fullPath: '/parent/transactions'
      preLoaderRoute: typeof ParentTransactionsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/installments': {
      id: '/admin/installments'
      path: '/installments'
      fullPath: '/admin/installments'
      preLoaderRoute: typeof AdminInstallmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminInstallmentsRoute: typeof AdminInstallmentsRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminInstallmentsRoute: AdminInstallmentsRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentTransactionsRoute: typeof ParentTransactionsRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentDashboardRoute: ParentDashboardRoute,
  ParentTransactionsRoute: ParentTransactionsRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface TeacherRouteChildren {
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  SignupRoute: SignupRoute,
  TeacherRoute: TeacherRouteWithChildren,
  PaymentCallbackRoute: PaymentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
